### ISSUE TITLE
asserts.is_class_instance does not work, klass is always Null inside implementation

### ISSUE THREAD

**Issue by angyan** [CodeDarigan/WAT-GDScript#147]
asserts.is_class_instance does not work, klass is always Null inside implementation

**Comment by CodeDarigan** [comment]
What version of Gadot are you running?
And could you show me your test?

You may also want to check if your object is null before you pass it in.

**Comment by angyan** [comment]
I'm using Godot version 3.2 and I did check that the object is not null. Let me put in some sample code :)

**Comment by CodeDarigan** [comment]
Closing until further notice. No apparent issues on my end.
