### ISSUE TITLE
Unable to use asserts.signal_was_not_emitted

### ISSUE THREAD

**Issue by angyan** [CodeDarigan/WAT-GDScript#148]
self.success = emitter.get_meta("watcher").watching[_signal].emit_count <= 0

Getting error: "Invalid get index 'watching' (on base 'Nil')'. where get_meta("watcher") returns nil.

**Comment by angyan** [comment]
Closing,

**Comment by angyan** [comment]
This doesn't work for any signal assertion.

**Comment by CodeDarigan** [comment]
Did you pass the emitter and signal into watch() before hand?

**Comment by CodeDarigan** [comment]
Any update on this or your other issue?

**Comment by CodeDarigan** [comment]
Closing until further notice. No apparent problems on my end.
