### ISSUE TITLE
Add Button to Test Failure Details to Open Test File in Editor - Feature Request

### ISSUE THREAD

**Issue by FeralBytes** [CodeDarigan/WAT-GDScript#176]
I would like to request a feature that allows me to have a button that will open the specified test file that had the failure, as compared to doing the mental context switch of: wait what file was that test part of and then digging into my test directories.

Thank you for WAT and if you are able to get this accomplished I would appreciate the feature, to help me focus even more.

**Comment by CodeDarigan** [comment]
This already exists. To the right-side of the failed test functions, you will see a fancy f icon. That f icon is a button that will open that functions script in the script editor.

![gotofunc](https://user-images.githubusercontent.com/47497501/103707476-994c1e00-4fa6-11eb-9bcf-d2a1f80b2133.png)

Its a little bit broken in master where it will just only open the script. However in the next release it will go directly to the function signature of the failed method in question.

**Comment by FeralBytes** [comment]
Awesome and I see it is documented here: https://wat.readthedocs.io/en/latest/pages/tutorials/using_the_gui.html#inspecting-the-test
