### ISSUE TITLE
Add Key Shortcuts

### ISSUE THREAD

**Issue by CodeDarigan** [CodeDarigan/WAT-GDScript#78]
Add option to set shortcuts to run tests.

Should probably allow for changing them as well (as well as checking to see if they override anything).

**Comment by atorstling-mojang** [comment]
Could you reopen this one? Would be great with a shortcut for running all tests

**Comment by CodeDarigan** [comment]
Reopening. Adding image to help me give context for when I get around to it. 
![image](https://user-images.githubusercontent.com/47497501/102835042-94576e00-43ed-11eb-9eec-ad37b2b9a09e.png)

**Comment by CodeDarigan** [comment]
@atorstling-mojang While a run all shortcut key is obvious, suggestions for any other shortcuts?

**Comment by CodeDarigan** [comment]
Resolved by https://github.com/CodeDarigan/WAT-GDScript/commit/4f68a61d57211db76c51bf36660bf1baed3a2da6

This is a tentative solution until https://github.com/godotengine/godot-proposals/issues/2024 is implemented (if at all).

Default shortcut is ctrl+shift+a to run all, you can change this manually by changing the shortcut in the inspector of the QuickStart Button that is on the gui.tscn which is in the top level folder of addons/WAT/gui.tscn

**Comment by atorstling-mojang** [comment]
Thank you @CodeDarigan and sorry for the late answer. Run all is what I was after, yes.
